---

name: 'Dependency Review'

on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142  # tag=v2.7.0
        with:  # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit
      - name: 'Checkout Repository'
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633  # tag=v4.1.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70  # tag=v4.3.2
