---

name: 'Dependency Review'

on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10  # tag=v2.8.0
        with:  # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit
      - name: 'Checkout Repository'
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633  # tag=v4.1.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@5bbc3ba658137598168acb2ab73b21c432dd411b  # tag=v4.2.5
